// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mZnVJYQ8TvuHu2pcRkTz7hDCCykWnCY',
    appId: '1:309731814290:web:febb525426d21f1f8eef4b',
    messagingSenderId: '309731814290',
    projectId: 'fir-flutter-codelab2-1d685',
    authDomain: 'fir-flutter-codelab2-1d685.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab2-1d685.appspot.com',
    measurementId: 'G-56YLBHDX36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnu5HtRBUqlRGpDQEPRRn6-o9OBJSuGmY',
    appId: '1:309731814290:android:6f8f84c7ae7aed0a8eef4b',
    messagingSenderId: '309731814290',
    projectId: 'fir-flutter-codelab2-1d685',
    storageBucket: 'fir-flutter-codelab2-1d685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUYV35wvCtvYZNSuRXuB18loWUvAwwAh8',
    appId: '1:309731814290:ios:49f7c8d7cb18e80c8eef4b',
    messagingSenderId: '309731814290',
    projectId: 'fir-flutter-codelab2-1d685',
    storageBucket: 'fir-flutter-codelab2-1d685.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUYV35wvCtvYZNSuRXuB18loWUvAwwAh8',
    appId: '1:309731814290:ios:49f7c8d7cb18e80c8eef4b',
    messagingSenderId: '309731814290',
    projectId: 'fir-flutter-codelab2-1d685',
    storageBucket: 'fir-flutter-codelab2-1d685.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
